#
# Copyright (c) 2023 ZettaScale Technology
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
# which is available at https://www.apache.org/licenses/LICENSE-2.0.
#
# SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
#
# Contributors:
#   ZettaScale Zenoh Team, <zenoh@zettascale.tech>
#
name: CI (Ubuntu)

on:
  workflow_call:

env:
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse
  DEBIAN_FRONTEND: noninteractive
  WIRESHARK_VERSION: 4.4

jobs:
  check:
    name: Run checks on Ubuntu
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-22.04]

    steps:
      - uses: actions/checkout@v4

      - run: cargo fmt -- --check

      - name: Install dependencies
        run: |
          sudo apt install -y software-properties-common
          # Disabled due to https://gitlab.com/wireshark/wireshark/-/issues/20505
          #sudo add-apt-repository -y ppa:wireshark-dev/stable
          #sudo apt install -y wireshark-dev
          #sudo apt install -y --allow-change-held-packages wireshark
          # Manually download and install previous package version that doesn't depend on libgio-2.0-dev
          wireshark_files=(
            'libwireshark-data_4.4.6-1~ubuntu24.04.0~ppa1_all.deb'
            'libwireshark18_4.4.6-1~ubuntu24.04.0~ppa1_amd64.deb'
            'libwsutil16_4.4.6-1~ubuntu24.04.0~ppa1_amd64.deb'
            'libwsutil-dev_4.4.6-1~ubuntu24.04.0~ppa1_amd64.deb'
            'libwiretap15_4.4.6-1~ubuntu24.04.0~ppa1_amd64.deb'
            'libwiretap-dev_4.4.6-1~ubuntu24.04.0~ppa1_amd64.deb'
            'libwireshark-dev_4.4.6-1~ubuntu24.04.0~ppa1_amd64.deb'
            'wireshark-common_4.4.6-1~ubuntu24.04.0~ppa1_amd64.deb'
            'wireshark-dev_4.4.6-1~ubuntu24.04.0~ppa1_amd64.deb'
            'wireshark-doc_4.4.6-1~ubuntu24.04.0~ppa1_all.deb'
            'wireshark_4.4.6-1~ubuntu24.04.0~ppa1_amd64.deb'
            'tshark_4.4.6-1~ubuntu24.04.0~ppa1_amd64.deb'
          )
          for filename in "${wireshark_files[@]}"; do
            wget https://launchpad.net/~wireshark-dev/+archive/ubuntu/stable/+files/$filename
            sudo dpkg -i $filename
          done

      - name: Clippy
        run: cargo clippy --all-targets -- --deny warnings

      - name: Build
        run: cargo build --release

      - name: Place the plugin
        run: |
          mkdir -p ~/.local/lib/wireshark/plugins/${{ env.WIRESHARK_VERSION }}/epan
          cp ./target/release/libzenoh_dissector.so ~/.local/lib/wireshark/plugins/${{ env.WIRESHARK_VERSION }}/epan/libzenoh_dissector.so

      - name: Test the sample data
        run: |
          # Disabled due to same issue as above
          #sudo apt install -y tshark
          [ $(tshark -r assets/sample-data.pcap | grep Zenoh | wc -l) -eq 7 ] || return 1
